<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <PropertyGroup>
    <!--Disables checking for a required property, because we are testing one parameter at a time-->
    <!--And disable forcing internal, as test classes must be public-->
    <NoWarn>$(NoWarn);RZ2012;CA1515</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Bunit" />
    <Using Include="Bunit.TestDoubles" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="bunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Wader.Bootstrap\Wader.Bootstrap.csproj" />
  </ItemGroup>
</Project>
