<Project>
  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <!-- TODO: Generate proper documentation -->
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup>
    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
    <CIBuild Condition="'$(CI)' == 'True'">true</CIBuild>
    <CIBuild Condition="'$(CI)' != 'True'">false</CIBuild>
  </PropertyGroup>
  <Import Project="$(RepoRoot)eng/VersionNumber.props" />
  <Import Project="$(RepoRoot)eng/BuildInfo.props" />
  <Import Project="$(RepoRoot)eng/DefaultPackages.props" />
</Project>
