<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <!--Disable forcing internal, most classes must be public (components) -->
    <NoWarn>$(NoWarn);CA1515</NoWarn>
    <DoNotPublishNuGet>true</DoNotPublishNuGet>
  </PropertyGroup>
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference
      Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer"
      PrivateAssets="all"
    />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Wader.Icons\Wader.Icons.csproj" />
    <ProjectReference Include="..\Wader.Bootstrap\Wader.Bootstrap.csproj" />
  </ItemGroup>
</Project>
