<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <!--Disable forcing internal, most classes must be public (components) -->
    <NoWarn>$(NoWarn);CA1515</NoWarn>
    <!-- Overwrite target framework beause this is a consumer of the code,
          moreover, the debugger couldn't attach when multiple frameworks were set up -->
    <TargetFramework>net10.0</TargetFramework>
    <!--suppress CheckTagEmptyBody, MsbuildTargetFrameworkTagInspection -->
    <TargetFrameworks></TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference
      Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer"
      PrivateAssets="all"
    />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Wader.Icons\Wader.Icons.csproj"/>
    <ProjectReference Include="..\Wader.Bootstrap\Wader.Bootstrap.csproj"/>
  </ItemGroup>
</Project>
