<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <BootstrapVersion>5.3.8</BootstrapVersion>
  </PropertyGroup>
  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>.\obj</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <SupportedPlatform Include="browser" />
    <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
    <!-- Enable NSubtitute to access internals -->
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Helpers\Stacks\BsHstack.razor.cs">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>
</Project>
