<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <AnalysisMode>All</AnalysisMode>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <PropertyGroup>
    <PackageProjectUrl>https://github.com/RiRiSharp/Wader</PackageProjectUrl>
    <RepositoryUrl>https://github.com/RiRiSharp/Wader.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Deterministic>true</Deterministic>
    <GenerateDocumentationFile>false</GenerateDocumentationFile> <!-- TODO: Generate proper
    documentation -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IsPackable>true</IsPackable>
    <IncludeBuildOutput>true</IncludeBuildOutput>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CSharpier.MsBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\"
      Condition="Exists('../../README.md')" />
    <None
      Include="../../branding/logo.png"
      Pack="true"
      PackagePath="\"
      Condition="Exists('../../branding/logo.png')"
    />
  </ItemGroup>
</Project>