<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <BootstrapIconsVersion>1.13.1</BootstrapIconsVersion>
    <PhosphorIconsVersion>2.0.8</PhosphorIconsVersion>
  </PropertyGroup>
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Wader\Wader.csproj" />
  </ItemGroup>
  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\fonts\bootstrap-icons.woff" />
    <_ContentIncludedByDefault Remove="wwwroot\fonts\bootstrap-icons.woff2" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\sprites\bootstrap\" />
  </ItemGroup>
</Project>
