name: publish-alpha

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Restore
        working-directory: src
        run: dotnet restore

      # For <VersionPrefix>1.2.3</VersionPrefix>, adds the suffix: <VersionSuffix>alpha-<run_number></VersionSuffix>
      - name: Build & Pack (Release)
        working-directory: src
        run: |
          VERSION_SUFFIX="alpha-${{ github.run_number }}"
          dotnet pack --configuration Release --no-restore \
            -p:VersionSuffix="$VERSION_SUFFIX" \
            -p:ContinuousIntegrationBuild=true \
            -o artifacts

      - name: Push nupkg
        working-directory: src
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          find artifacts -name "*.nupkg" -print0 | xargs -0 -I{} \
            dotnet nuget push "{}" \
              --api-key "$NUGET_API_KEY" \
              --source https://api.nuget.org/v3/index.json \
              --skip-duplicate

      - name: Push snupkg
        working-directory: src
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          find artifacts -name "*.snupkg" -print0 | xargs -0 -I{} \
            dotnet nuget push "{}" \
              --api-key "$NUGET_API_KEY" \
              --source https://api.nuget.org/v3/index.json \
              --skip-duplicate